# This is a basic workflow to help you get started with Actions

name: macOS Package

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.7.0'
          modules: 'qtmultimedia'
      - name: Build
        working-directory: ./
        run: |
          cmake -B build .
          cmake --build build -j
      - name: Package
        id: package
        working-directory: ./
        continue-on-error: true
        run: |
          macdeployqt build/thplayer.app
          zip -r9 --symlinks thplayer-macos.zip thplayer.app
      - name: Upload
        if: steps.package.conclusion == 'success'
        uses: actions/upload-artifact@v4
        with:
          name: macOS-Build
          path: thplayer-macos.zip
